FROM centos:7

# Install devtoolset-8 (gcc 8)
RUN yum install -y centos-release-scl && \
    yum install -y devtoolset-8

ENV PATH /opt/rh/devtoolset-8/root/usr/bin:$PATH
ENV LD_LIBRARY_PATH /opt/rh/devtoolset-8/root/usr/lib64:/opt/rh/devtoolset-8/root/usr/lib:$LD_LIBRARY_PATH

# Build command
# > docker build -f Dockerfile.gcc -t gmao/compiler-gcc:8.2.1 .
