FROM centos:7

# Install devtoolset-9 (gcc 9)
RUN yum install -y centos-release-scl && \
    yum install -y devtoolset-9

ENV PATH /opt/rh/devtoolset-9/root/usr/bin:$PATH
ENV LD_LIBRARY_PATH /opt/rh/devtoolset-9/root/usr/lib64:/opt/rh/devtoolset-9/root/usr/lib:$LD_LIBRARY_PATH

CMD gfortran --version

# Build command
# > docker build -f Dockerfile.gcc -t gmao/compiler-gcc:9.1.1 .
